### ISSUE TITLE
Renommer les labels en francais ?

### ISSUE THREAD

**Issue by GuillaumeBelz** [NotANameServer/discord#15]
Il y a des labels en anglais et en français. Ça serait probablement mieux d'uniformiser tout en francais. Idem pour les descriptions.

Uniformiser aussi les majuscules

Accepté -> accepté (majuscule)
duplicate -> duplicata ou doublon
enhancement -> amélioration
good first issue -> pour débuter 
help wanted -> aide recherchée
invalid -> invalide
wontfix -> ~~ne pas corriger~~

EDIT: a priori, tout le monde peut modifier les labels. Je peux faire directement les changements proposés, si pas d'objection.

Par contre, ça serait peut être une bonne chose que les labels ne soient pas modifiables par tout le monde.

- [ ] renommer les labels en francais
- [x] idem pour les descriptions
- [x] uniformiser les majuscules
- [x] bloquer les droits d'édition des labels

**Comment by GuillaumeBelz** [comment]
A mon avis, il y a des labels en doublon ou trop proche pour être facilement compréhensibles

- accepté et implémenté
- rejeté et wontfix

A mon sens, on peut virer, pour eviter les confusions

**Comment by GuillaumeBelz** [comment]
j'ai fait quelques mises a jour des labels, pour simplifier leur utilisation et compréhension.

- il y a 3 catégories de labels (1, 2 et 3), chaque issue doit avoir un label de chaque catégorie (a priori)
- la catégorie 1 correspond a quel endroit est concerné par le label : le discord, le github ou la documentation
- la catégorie 2 correspond au type de l'issue : amelioration, bug, question
- la catégorie 3 correspond a l'avancement de l'issue : en discussion, accepté (ie on est d'accord et c'est en cours d'implémentation) ou fermée (fini = accepté et implémentée, invalide = l'issue n'a pas de sens, rejeté = l'issue a un sens mais n'est pas souhaitable)
- il y a des labels pour ajouter des précisions sur l'issue : demande d'aide, issue pour débuter, doublon

**Comment by Mesteery** [comment]
perso je trouve que les catégories embrouillent (1, 2 ou 3) plus qu'autre chose. Le nom seul avec une bonne description suffit.

**Comment by GuillaumeBelz** [comment]
Je ne sais pas très bien :) C'est un label qui existait déjà. Je l'ai ajouté par exemple a https://github.com/NotANameServer/discord/issues/13

> perso je trouve que les catégories embrouillent (1, 2 ou 3) plus qu'autre chose. Le nom seul suffit.

cela permet en en clin d'oeil dans la liste des issues de visualiser rapidement. Et d'avoir les labels triés dans la liste des labels. C'est surtout pour faciliter la gestion des labels

**Comment by Mesteery** [comment]
> cela permet en en clin d'oeil dans la liste des issues de visualiser rapidement. Et d'avoir les labels triés dans la liste des labels. C'est surtout pour faciliter la gestion des labels

perso je trouve que se repère très bien sans, en soit les couleurs servent déjà comme catégorie, et c'est aussi visuelle

**Comment by GuillaumeBelz** [comment]
J'ai mit effectivement les couleurs pour que ce soit plus clair. Les numéros, c'est juste pour avoir les labels triés par catégories.

Si les numéros n'ont pas un impact négatif, c'est mieux de les garder.

**Comment by Mesteery** [comment]
moi je sais que les numéros je vais jamais retenir on pourrait pas avoir par exemple des noms tels que `type: amélioration`, `scope: github`, `état: en discussion`

**Comment by GuillaumeBelz** [comment]
il n'est pas nécessaire de les retenir. Quand tu vois la liste des issue et des labels, ca me semble assez compréhensible justement.

Mais je ne suis pas sûr que les gens ont accès en édition aux labels. C'est juste les admins qui peuvent les modifier.

**Comment by GuillaumeBelz** [comment]
J'ai modifié les labels de la catégorie 2 pour tester ta proposition. A voir avec le temps et d'autres avis ce qui plait le plus.

Ca me fait penser que j'ai vu récemment des labels qui avaient justement un type associé au label. Il faudrait que je retrouve ca.

**Comment by Mesteery** [comment]
> Mais je ne suis pas sûr que les gens ont accès en édition aux labels. C'est juste les admins qui peuvent les modifier.
Oui les collaborateurs. Mais c'est pas ça que je voulais dire je proposais juste respectivement `scope`, `type` et `état` au lieux des numéros

**Comment by Julien00859** [comment]
J'ai du lire les issues pour comprendre ce que voulaient dire les 1/2/3, je suis +1 avec mestery pour scope/type/état

**Comment by GuillaumeBelz** [comment]
Fais pour `github/meta`, mais pas sur que ce soit clair.

Pour les nombres, je peux comprendre. J'ai fait le changement, on va voir ce que cela donne.

Par contre, "scope" est de l'anglais.

**Comment by Mesteery** [comment]
> Par contre, "scope" est de l'anglais.
ouai comme plusieurs autres labels mais bon, faut trouver un nom en français aussi beau que celui-ci

**Comment by GuillaumeBelz** [comment]
Sauf oubli, tout a été traduit en francais.

**Comment by Julien00859** [comment]
:100: qu'on change directement et qu'on voit ce que ça donne :)

**Comment by GuillaumeBelz** [comment]
A priori, cette discussion est close pour le moment. On pourra creer un nouvelle issue si quelqu'un souhaite proposer des ameliorations/correction
